version: '2'
services:
    sources-app:
        image: sources
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sources-mysql:3306/sources?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sources-mysql:
        extends:
            file: mysql.yml
            service: sources-mysql
